### PR TITLE
module: init Go module support

### PR DESCRIPTION
**Pull request by zchee**
init Go module support.

### CODE REVIEW

**Comment by zchee** [comment]
cc: @zimmski @sbinet

**Comment by sbinet** [comment]
could you please rebase on the latest `master` (that includes your latest Go-version bump on travis) ?
this should fix the travis failure.

thanks again.

**Comment by zchee** [comment]
@sbinet yes, I thought it.
will do.

**Comment by zchee** [comment]
@sbinet PTAL.

**Review by sbinet — APPROVED** [review]

**Comment by zchee** [comment]
@sbinet ah, CI failed because maybe I'm already a go-clang org member but this branch is my forked repo.
I'll re-create the pull request.

**Comment by zchee** [comment]
CI is passed. merge.

**Pull request merged**
